routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/setup', 'SetupController')->only('edit', 'update');

Route::resource('/akreditasi', 'RankAkreditasiController');
Route::resource('/dosen', 'RankDosenController');
Route::resource('/fasilitas', 'RankFasilitasController');
Route::resource('/lokasi', 'RankLokasiController');
Route::resource('/universitas', 'UniversitasController');

Route::resource('/proses', 'SpkController')->only('index', 'store');
Route::resource('/history', 'HistoryController')->only('index');

app/Universitas.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Universitas extends Model
{
    protected $fillable = [
        'nama',
        'alamat',
        'rank_akreditasi_id',
        'rank_dosen_id',
        'rank_fasilitas_id',
        'rank_lokasi_id',
        'rank_keseluruhan',
    ];

    public function akreditasi()
    {
        return $this->belongsTo('\App\RankAkreditasi', 'rank_akreditasi_id');
    }

    public function dosen()
    {
        return $this->belongsTo('\App\RankDosen', 'rank_dosen_id');
    }

    public function fasilitas()
    {
        return $this->belongsTo('\App\RankFasilitas', 'rank_fasilitas_id');
    }

    public function lokasi()
    {
        return $this->belongsTo('\App\RankLokasi', 'rank_lokasi_id');
    }
}

app/Http/Controllers/UniversitasController.php
<?php

namespace App\Http\Controllers;

use App\RankDosen;
use App\RankLokasi;
use App\Universitas;
use App\RankFasilitas;
use App\RankAkreditasi;
use Illuminate\Http\Request;

class UniversitasController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $data = Universitas::orderBy('nama')->get();
        return view('universitas.index', compact('data'));
    }

    public function create()
    {
        return view('universitas.create');
    }

    public function store(Request $r)
    {
        $data = $r->validate([
            'nama' => 'required',
            'alamat' => 'required',
            'rank_akreditasi_id' => 'required|numeric',
            'rank_dosen_id' => 'required|numeric',
            'rank_fasilitas_id' => 'required|numeric',
            'rank_lokasi_id' => 'required|numeric',
        ]);

        $a = Universitas::make($data);

        $akreditasi = RankAkreditasi::find($r->rank_akreditasi_id)->rank;
        $dosen      = RankDosen::find($r->rank_dosen_id)->rank;
        $fasilitas  = RankFasilitas::find($r->rank_fasilitas_id)->rank;
        $lokasi     = RankLokasi::find($r->rank_lokasi_id)->rank;

        $a->rank_keseluruhan = $akreditasi + $dosen + $fasilitas + $lokasi;
        $a->save();

        return redirect('universitas');
    }

    public function edit($id)
    {
        $data = Universitas::find($id);
        return view('universitas.edit', compact('data'));
    }

    public function update(Request $r, $id)
    {
        $data = $r->validate([
            'nama' => 'required',
            'alamat' => 'required',
            'rank_akreditasi_id' => 'required|numeric',
            'rank_dosen_id' => 'required|numeric',
            'rank_fasilitas_id' => 'required|numeric',
            'rank_lokasi_id' => 'required|numeric',
        ]);

        $a = Universitas::find($id);
        $a->update($data);

        $akreditasi = RankAkreditasi::find($r->rank_akreditasi_id)->rank;
        $dosen      = RankDosen::find($r->rank_dosen_id)->rank;
        $fasilitas  = RankFasilitas::find($r->rank_fasilitas_id)->rank;
        $lokasi     = RankLokasi::find($r->rank_lokasi_id)->rank;

        $a->rank_keseluruhan = $akreditasi + $dosen + $fasilitas + $lokasi;
        $a->save();

        return redirect('universitas');
    }

    public function destroy($id)
    {
        $a = Universitas::destroy($id);
        return redirect('universitas');
    }

}

resources/views/universitas/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h3>Universitas - Input Baru</h3>
            <div class="bootstrap-iso">
                <a href="{{ URL::to('/universitas') }}" class="btn btn-default">Kembali</a>
            </div>
            <hr>
            <form class="form-horizontal" method="POST" action="{{ url('universitas') }}">
            {{ csrf_field() }}

                <div class="box-body">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nama</label>
                        <div class="col-sm-6">
                            <input class="form-control" name="nama" placeholder="Nama Universitas">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Alamat</label>
                        <div class="col-sm-12">
                            <input class="form-control" name="alamat" placeholder="Alamat Universitas">
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="col-sm-2 control-label">Akreditasi</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="rank_akreditasi_id" id="rank_akreditasi">
                                @foreach (\App\RankAkreditasi::akreditasi() as $k=>$v)
                                    <option value="{{ $v->id }}">{{ $v->keterangan }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Dosen</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="rank_dosen_id" id="rank_dosen">
                                @foreach (\App\RankDosen::dosen() as $k=>$v)
                                    <option value="{{ $v->id }}">{{ $v->keterangan }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Fasilitas</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="rank_fasilitas_id" id="rank_fasilitas">
                                @foreach (\App\RankFasilitas::fasilitas() as $k=>$v)
                                    <option value="{{ $v->id }}">{{ $v->keterangan }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Lokasi</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="rank_lokasi_id" id="rank_lokasi">
                                @foreach (\App\RankLokasi::lokasi() as $k=>$v)
                                    <option value="{{ $v->id }}">{{ $v->keterangan }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                </div>

                <div class="box-footer bootstrap-iso">
                    <button id="simpan" type="submit" class="btn btn-primary" hidden>Simpan Data</button>
                    <a href="javascript:cek()" class="btn btn-primary">Simpan Data</a>
                </div>

            </form>
            <hr>
        </div>
    </div>
</div>

<script type="text/javascript">

	function cek()
	{
		let a = confirm("Simpan Data?");
        if(a) {
            $('#simpan').click();
        }
	}

</script>

@endsection

resources/views/universitas/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <h3>Universitas - Edit Data</h3>
            <div class="bootstrap-iso">
                <a href="{{ URL::to('/universitas') }}" class="btn btn-default">Kembali</a>
            </div>
            <hr>
            <form class="form-horizontal" method="POST" action="{{ url('universitas', $data->id) }}">
            {{ csrf_field() }}
            <input name="_method" type="hidden" value="PATCH">

                <div class="box-body">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Nama</label>
                        <div class="col-sm-6">
                            <input class="form-control" name="nama" placeholder="Nama Universitas" value="{{ $data->nama }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Alamat</label>
                        <div class="col-sm-12">
                            <input class="form-control" name="alamat" placeholder="Alamat Universitas" value="{{ $data->alamat }}">
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="col-sm-2 control-label">Akreditasi</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="rank_akreditasi_id" id="rank_akreditasi">
                                @foreach (\App\RankAkreditasi::akreditasi() as $k=>$v)
                                    <option value="{{ $v->id }}">{{ $v->keterangan }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Dosen</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="rank_dosen_id" id="rank_dosen">
                                @foreach (\App\RankDosen::dosen() as $k=>$v)
                                    <option value="{{ $v->id }}">{{ $v->keterangan }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Fasilitas</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="rank_fasilitas_id" id="rank_fasilitas">
                                @foreach (\App\RankFasilitas::fasilitas() as $k=>$v)
                                    <option value="{{ $v->id }}">{{ $v->keterangan }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Lokasi</label>
                        <div class="col-sm-3">
                            <select class="form-control" name="rank_lokasi_id" id="rank_lokasi">
                                @foreach (\App\RankLokasi::lokasi() as $k=>$v)
                                    <option value="{{ $v->id }}">{{ $v->keterangan }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>

                </div>

                <div class="box-footer bootstrap-iso">
                    <button id="simpan" type="submit" class="btn btn-primary" hidden>Simpan Data</button>
                    <a href="javascript:cek()" class="btn btn-primary">Simpan Data</a>
                </div>

            </form>
            <hr>
        </div>
    </div>
</div>

<script type="text/javascript">

	function cek()
	{
		let a = confirm("Simpan Data?");
        if(a) {
            $('#simpan').click();
        }
	}

    $("#rank_akreditasi").val("{{ $data->rank_akreditasi_id }}");
    $("#rank_dosen").val("{{ $data->rank_dosen_id }}");
    $("#rank_fasilitas").val("{{ $data->rank_fasilitas_id }}");
    $("#rank_lokasi").val("{{ $data->rank_lokasi_id }}");

</script>

@endsection

resources/views/universitas/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
	    	        <h3>Universitas</h3>
                </div>

                <div class="card-body">

                    <a class="btn btn-primary btn-md" onclick='createItem()'>Input Baru</a>
                    <hr>
                    <table id="datatable" class="table table-striped">
                        <thead>
                            <tr>
                                <td style="text-align: center;"><b>Nama</b></td>
                                <td style="text-align: center;"><b>Alamat </b></td>
                                <td style="text-align: center;"><b>Grade/Rank<br>Akreditasi</b></td>
                                <td style="text-align: center;"><b>Grade/Rank<br>Dosen</b></td>
                                <td style="text-align: center;"><b>Grade/Rank<br>Fasilitas</b></td>
                                <td style="text-align: center;"><b>Grade/Rank<br>Lokasi</b></td>
                                <td style="text-align: center;"><b>Grade/Rank<br>Keseluruhan</b></td>
                                <td style="text-align: center;"><b>Act</b></td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($data as $k=>$v)
                            <tr>
                                <td style="text-align: left;">{{ $v->nama }}</td>
                                <td style="text-align: left;">{{ $v->alamat }}</td>
                                <td style="text-align: center;">
                                    {{ strtoupper($v->akreditasi->keterangan) }}<br>
                                    ({{ strtoupper($v->akreditasi->grade) }} / {{ $v->akreditasi->rank }})
                                </td>
                                <td style="text-align: center;">
                                    {{ strtoupper($v->dosen->keterangan) }}<br>
                                    ({{ strtoupper($v->dosen->grade) }} / {{ $v->dosen->rank }})
                                </td>
                                <td style="text-align: center;">
                                    {{ strtoupper($v->fasilitas->keterangan) }}<br>
                                    ({{ strtoupper($v->fasilitas->grade) }} / {{ $v->fasilitas->rank }})
                                </td>
                                <td style="text-align: center;">
                                    {{ strtoupper($v->lokasi->keterangan) }}<br>
                                    ({{ strtoupper($v->lokasi->grade) }} / {{ $v->lokasi->rank }})
                                </td>
                                <td style="text-align: center;">{{ $v->rank_keseluruhan }}</td>
                                <td class="bootstrap-iso">
                                    <div class="text-center">
                                        <form action="{{ route('universitas.destroy', $v) }}" method="post">
                                            @csrf
                                            @method('delete')

                                            <a class="btn btn-success btn-sm" onclick="editItem('{{ $v->id }}')">Edit</a>
                                            <a class="btn btn-danger btn-sm" onclick="confirm('{{ __("Hapus data?") }}') ? this.parentElement.submit() : ''">Hapus</a>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

	function createItem()
	{
		location.href="/universitas/create";
	}

	function editItem(id)
	{
		location.href="/universitas/"+id+"/edit";
	}

</script>

@endsection