routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/setup', 'SetupController')->only('edit', 'update');

Route::resource('/akreditasi', 'RankAkreditasiController');
Route::resource('/dosen', 'RankDosenController');
Route::resource('/fasilitas', 'RankFasilitasController');
Route::resource('/lokasi', 'RankLokasiController');
Route::resource('/universitas', 'UniversitasController');

Route::resource('/proses', 'SpkController')->only('index', 'store');
Route::resource('/history', 'HistoryController')->only('index');

resources/views/lokasi/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h3>Rank Lokasi - Input Baru</h3>
            <div class="bootstrap-iso">
                <a href="{{ URL::to('/lokasi') }}" class="btn btn-default">Kembali</a>
            </div>
            <hr>
            <form class="form-horizontal" method="POST" action="{{ url('lokasi') }}">
            {{ csrf_field() }}

                <div class="box-body">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Keterangan</label>
                        <div class="col-sm-12">
                            <input class="form-control" name="keterangan" placeholder="Keterangan">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Grade</label>
                        <div class="col-sm-6">
                            <input class="form-control" name="grade" placeholder="A / B / C">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Value/Rank</label>
                        <div class="col-sm-6">
                            <input class="form-control" type="number" min="1" name="rank" placeholder="Value/Rank">
                        </div>
                    </div>
                </div>

                <div class="box-footer bootstrap-iso">
                    <button id="simpan" type="submit" class="btn btn-primary" hidden>Simpan Data</button>
                    <a href="javascript:cek()" class="btn btn-primary">Simpan Data</a>
                </div>

            </form>
            <hr>
        </div>
    </div>
</div>

<script type="text/javascript">

	function cek()
	{
		let a = confirm("Simpan Data?");
        if(a) {
            $('#simpan').click();
        }
	}

</script>

@endsection

resources/views/lokasi/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h3>Rank Lokasi - Edit Data</h3>
            <div class="bootstrap-iso">
                <a href="{{ URL::to('/lokasi') }}" class="btn btn-default">Kembali</a>
            </div>
            <hr>
            <form class="form-horizontal" method="POST" action="{{ url('lokasi', $data->id) }}">
                {{ csrf_field() }}
                <input name="_method" type="hidden" value="PATCH">

                <div class="box-body">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">Keterangan</label>
                        <div class="col-sm-12">
                            <input class="form-control" name="keterangan" placeholder="Keterangan" value="{{ $data->keterangan }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Grade</label>
                        <div class="col-sm-6">
                            <input class="form-control" name="grade" placeholder="A / B / C" value="{{ $data->grade }}">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-sm-2 control-label">Value/Rank</label>
                        <div class="col-sm-6">
                            <input class="form-control" type="number" min="1" name="rank" placeholder="Value/Rank" value="{{ $data->rank }}">
                        </div>
                    </div>
                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-success">Update Data</button>
                </div>

            </form>
            <hr>
        </div>
    </div>
</div>

<script type="text/javascript">

	function cek()
	{
		let a = confirm("Rubah Data?");
        if(a) {
            $('#simpan').click();
        }
	}

</script>

@endsection

resources/views/lokasi/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
	    	        <h3>Ranking Lokasi</h3>
                </div>

                <div class="card-body">

                    <a class="btn btn-primary btn-md" onclick='createItem()'>Input Baru</a>
                    <hr>
                    <table id="datatable" class="table table-striped">
                        <thead>
                            <tr>
                                <td style="text-align: center;"><b>Keterangan</b></td>
                                <td style="text-align: center;"><b>Grade </b></td>
                                <td style="text-align: center;"><b>Value/Rank </b></td>
                                <td style="text-align: center;"><b>Act</b></td>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach ($data as $k=>$v)
                            <tr>
                                <td style="text-align: left;">{{ $v->keterangan }}</td>
                                <td style="text-align: center;">{{ $v->grade }}</td>
                                <td style="text-align: center;">{{ $v->rank }}</td>
                                <td class="bootstrap-iso">
                                    <div class="text-center">
                                        <form action="{{ route('lokasi.destroy', $v) }}" method="post">
                                            @csrf
                                            @method('delete')

                                            <a class="btn btn-success btn-sm" onclick="editItem('{{ $v->id }}')">Edit</a>
                                            <a class="btn btn-danger btn-sm" onclick="confirm('{{ __("Hapus data?") }}') ? this.parentElement.submit() : ''">Hapus</a>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

	function createItem()
	{
		location.href="/lokasi/create";
	}

	function editItem(id)
	{
		location.href="/lokasi/"+id+"/edit";
	}

</script>

@endsection